on:
  port: 8080
  address: 0.0.0.0

jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/employees
  username: root
  password: 12345678

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect